# Generated by Django 2.1.1 on 2018-10-08 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('uid', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=128)),
                ('update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('status', models.CharField(max_length=128)),
                ('hashtag', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('exit', models.IntegerField()),
                ('submit', models.IntegerField()),
                ('start', models.IntegerField()),
                ('process', models.CharField(max_length=128)),
                ('tag', models.CharField(max_length=128)),
                ('module', models.CharField(max_length=128)),
                ('container', models.CharField(max_length=128)),
                ('attempt', models.CharField(max_length=128)),
                ('script', models.CharField(max_length=128)),
                ('scratch', models.CharField(max_length=128)),
                ('workdir', models.CharField(max_length=128)),
                ('queue', models.CharField(max_length=128)),
                ('cpus', models.CharField(max_length=128)),
                ('memory', models.CharField(max_length=128)),
                ('disk', models.CharField(max_length=128)),
                ('time', models.CharField(max_length=128)),
                ('env', models.CharField(max_length=128)),
                ('native_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='trace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Logger.Trace'),
        ),
    ]
