# Generated by Django 2.1.1 on 2018-10-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='name',
            new_name='runId',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='status',
            new_name='runName',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='uid',
            new_name='runStatus',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='update',
            new_name='utcTime',
        ),
        migrations.RenameField(
            model_name='trace',
            old_name='hashtag',
            new_name='hash',
        ),
        migrations.AlterModelTable(
            name='record',
            table='logger_record',
        ),
    ]
