# Generated by Django 2.1.1 on 2018-10-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logger', '0005_remove_record_trace'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='error_action',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
