# Generated by Django 2.1.1 on 2018-10-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logger', '0006_trace_error_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='complete',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trace',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trace',
            name='realtime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
