# Generated by Django 2.1.1 on 2018-10-09 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Logger', '0007_auto_20181009_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='trace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Logger.Trace'),
        ),
    ]
