# Generated by Django 2.1.1 on 2018-10-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logger', '0010_auto_20181009_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trace',
            name='queue',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
