# Generated by Django 2.1.1 on 2018-10-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logger', '0011_auto_20181009_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trace',
            name='cpus',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='trace',
            name='disk',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='trace',
            name='memory',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
