# Generated by Django 2.1.1 on 2018-10-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logger', '0012_auto_20181009_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trace',
            name='env',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='trace',
            name='native_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trace',
            name='time',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
