# Generated by Django 2.1.1 on 2018-10-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logger', '0013_auto_20181009_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trace',
            name='container',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='trace',
            name='module',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
