# Generated by Django 2.1.1 on 2018-10-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logger', '0014_auto_20181009_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('runName', models.CharField(max_length=128)),
                ('runId', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('runStatus', models.CharField(max_length=128)),
                ('startedDatetime', models.DateTimeField(blank=True, null=True)),
                ('errorDatetime', models.DateTimeField(blank=True, null=True)),
                ('completedDatetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelTable(
            name='record',
            table=None,
        ),
    ]
