# Generated by Django 2.1.1 on 2018-10-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logger', '0015_auto_20181010_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('uid', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('runId', models.CharField(max_length=128)),
                ('runStatus', models.CharField(max_length=128)),
                ('startedDatetime', models.DateTimeField(blank=True, null=True)),
                ('submittedDatetime', models.DateTimeField(blank=True, null=True)),
                ('completedDatetime', models.DateTimeField(blank=True, null=True)),
                ('hashtag', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('exitcode', models.IntegerField(blank=True, null=True)),
                ('process', models.CharField(blank=True, max_length=128, null=True)),
                ('container', models.CharField(blank=True, max_length=128, null=True)),
                ('attempt', models.IntegerField(blank=True, null=True)),
                ('script', models.CharField(blank=True, max_length=512, null=True)),
                ('workdir', models.CharField(blank=True, max_length=128, null=True)),
                ('queue', models.CharField(blank=True, max_length=128, null=True)),
                ('cpus', models.IntegerField(blank=True, null=True)),
                ('memory', models.CharField(blank=True, max_length=16, null=True)),
                ('disk', models.CharField(blank=True, max_length=16, null=True)),
                ('time', models.CharField(blank=True, max_length=128, null=True)),
                ('env', models.CharField(blank=True, max_length=128, null=True)),
                ('error_action', models.CharField(blank=True, max_length=128, null=True)),
                ('native_id', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='run',
            name='runName',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='runStatus',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
