# Generated by Django 2.1.1 on 2018-10-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logger', '0016_auto_20181010_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='script',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
