# Generated by Django 2.1.1 on 2018-10-10 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Logger', '0017_auto_20181010_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Logger.Process'),
        ),
    ]
