# Generated by Django 2.1.1 on 2018-10-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logger', '0018_run_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='process',
        ),
        migrations.AddField(
            model_name='run',
            name='process',
            field=models.ManyToManyField(blank=True, to='Logger.Process'),
        ),
    ]
